# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}
  context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: vsftp-client
  http:
    multipart:
      max-file-size: ${HTTP_MULTIPART_MAX_FILE_SIZE:100MB}
      max-request-size: ${HTTP_MULTIPART_MAX_REQUEST_SIZE:100MB}

# FTP settings
ftp:
  port: ${FTP_PORT}
  host: ${FTP_HOST}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  connectTimeout: 60000
  dataTimeout: 60000
